# Generated by Django 3.0.10 on 2021-07-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_address_city'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permanent_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_phone',
            field=models.CharField(default='', max_length=32),
        ),
    ]
