# Generated by Django 3.0.10 on 2021-06-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210627_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.SmallIntegerField(choices=[(10, 20), (10, 20)], default=10),
            preserve_default=False,
        ),
    ]
