# Generated by Django 3.0.10 on 2021-07-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210712_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='contact',
            name='personal_phone',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
