# Generated by Django 3.0.10 on 2021-07-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=128)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='student.Employer')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='employment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='student.Employment'),
        ),
    ]
