# Generated by Django 3.0.10 on 2021-07-12 20:43

from django.db import migrations, models
import django.db.models.deletion
import student.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210712_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=512, upload_to=student.utils.storage.upload_to_student_dir)),
                ('type', models.SmallIntegerField(choices=[(10, 'photo'), (20, 'video')])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='student.Student')),
            ],
        ),
    ]
